substrate:
  num_nodes: 10
  edge_prob: 0.3
  cpu_range: [50, 100]
  bandwidth_range: [50, 100]

vnr:
  num_nodes: 3
  edge_prob: 0.5
  cpu_range: [10, 30]
  bandwidth_range: [10, 30]
  duration_range: [5, 10]

experiment:
  embedder: "random"      # ← "first_fit" や "greedy" に切り替え可能
  episodes: 20
  arrival_rate: 1.0
  seed: 42
  max_steps: 30
